### ISSUE TITLE
Collaborative Launch 1706536800 (2024-01-29 14:00 GMT, Kartograf v0.4.4)

### ISSUE THREAD

**Issue by fjahr** [fjahr/asmap-data#9]
Next collaborative launch is planned for `1706536800`. Please make sure to upgrade to Kartograf v0.4.4 which was released today (https://github.com/fjahr/kartograf/releases/tag/0.4.4).

```
./run map -w=1706536800 -irr -rv
```

https://github.com/fjahr/asmap-data/issues/7 wasn't a success but it was expected that not every run would have sufficient matches. The robustness improvement for the download issue should be an improvement though and the hashes of downloaded files are now printed in the output right away, which should make debugging mismatches a bit easier. I hope this one can the first clean run that concisely shows what the process could look like when being run routinely.

Thanks for your participation in advance! Upon completion please post your hash in the comments. When we have majority for one hash, we will open a PR, similar to https://github.com/fjahr/asmap-data/pull/6.

**Comment by fjahr** [comment]
My result hash this time: `608bdb0121d116ca2b1b958dce6cc538d09ca775084065ad4314cd5c893a2800`

<details><summary>And here are the logs with the file hashes</summary>

```
$ ./run map -w=1706536800 -irr -rv

--- Start Kartograf ---

Kartograf version: 0.4.4
Using rpki-client version 8.5.
Coordinated launch mode: Waiting until 1706536800 (2024-01-29 15:00:00 CET) to launch mapping process.
Countdown: 0 second(s)
Starting...
The epoch for this run is: 1706536800 (2024-01-29 14:00:00 UTC, local: 2024-01-29 15:00:00 CET)

--- Fetching RPKI ---

Downloaded TAL for AFRINIC to /Users/FJ/projects/python/kartograf/data/1706536800/rpki/tals/afrinic.tal, file hash: 2838ef30ea27ce5705abf5f5adb131d8c35b1f50858338a2f3c84bb207c2fa35
Downloaded TAL for APNIC to /Users/FJ/projects/python/kartograf/data/1706536800/rpki/tals/apnic.tal, file hash: 472e551f7c551c2e999e582b7c9437d3bee4900fe53afff62aeb28d4940ade94
Downloaded TAL for ARIN to /Users/FJ/projects/python/kartograf/data/1706536800/rpki/tals/arin.tal, file hash: 4f6c1e456fe5ab468beac1495e57d99a1eeeaa4d9f9e34519eaf58857c21af48
Downloaded TAL for LACNIC to /Users/FJ/projects/python/kartograf/data/1706536800/rpki/tals/lacnic.tal, file hash: d44bb9394ab009c8b53e5efebf2a1c9450bab61a27efe00de5a3e4587a3a2f6a
Downloaded TAL for RIPE to /Users/FJ/projects/python/kartograf/data/1706536800/rpki/tals/ripe.tal, file hash: 59ca27ef93f23682749fcefe7c6d70fbc723343549ff9e4d3996acaff79817fb
Downloading RPKI Data, this may take a while.
Downloaded RPKI Data, hash sum: e83c3d65283cdf332ef74d96cebfc2347fccdb0ee86eb560f7bf21385c14b186
...finished in 0:09:46.314704

--- Fetching IRR ---

Downloading afrinic.db.gz
Downloaded afrinic.db.gz, file hash: cca68427da15e925b3d380b81bea038eb6edc3ffacc0e9854ca706dc4297f966
Downloading apnic.db.route.gz
Downloaded apnic.db.route.gz, file hash: c043e482eb433e765e57a19d967d814f2e37761c91a281a22b4a3c3b9a0bc178
Downloading apnic.db.route6.gz
Downloaded apnic.db.route6.gz, file hash: b358c511eb573311b0b0888a15adc33f932aaa13deaf6b45c016715a7e8162fa
Downloading arin.db.gz
Downloaded arin.db.gz, file hash: b0477a606536ad2f48c1cd94357660ebbd7a16429ae1b19b8cf47bdc5664b66c
Downloading lacnic.db.gz
Downloaded lacnic.db.gz, file hash: 03bd7a0ccd6b56e3a1c2605ea9027ffee3feaf3dffa764dc9843629a0b1b1d26
Downloading ripe.db.route.gz
Downloaded ripe.db.route.gz, file hash: b946420fdb8820680d5a8977c81199939bb148fdf27caafc787b207d3b67cd5f
Downloading ripe.db.route6.gz
Downloaded ripe.db.route6.gz, file hash: eac33b8b823b34217936b1d6134cb652aa45205811d99ac70485f0b0b7f1a81f
...finished in 0:01:07.622632

--- Fetching Routeviews pfx2as ---

Downloading from https://publicdata.caida.org/datasets/routing/routeviews-prefix2as/2024/01/routeviews-rv2-20240127-1200.pfx2as.gz
Downloaded /Users/FJ/projects/python/kartograf/data/1706536800/collectors/routeviews_pfx2asn_ip4.txt.gz, file hash: f067cf350b2062818888c61c46c1110c788efc7a828d2dbf2ba45894be379f70
Downloading from https://publicdata.caida.org/datasets/routing/routeviews6-prefix2as/2024/01/routeviews-rv6-20240128-0600.pfx2as.gz
Downloaded /Users/FJ/projects/python/kartograf/data/1706536800/collectors/routeviews_pfx2asn_ip6.txt.gz, file hash: c1542e97ff4006425f0f702beebd28022b1bd2b1f5228448cbd5e94dff53f02d
...finished in 0:00:07.300277

--- Validating RPKI ---

Validating RPKI ROAs
218376 raw RKPI ROA files found.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 218376/218376 [39:04<00:00, 93.16it/s]
218376 RKPI ROAs validated and saved to /Users/FJ/projects/python/kartograf/out/1706536800/rpki/rpki_raw.json, file hash: ad441cf001b26258be0f8960dca72218b94e829ce93cd9db32d8e3664dbe9d5b
...finished in 0:39:36.927227

--- Parsing RPKI ---

Parsing 218376 ROAs
Result entries written: 457098
Duplicates found: 57634
Invalids found: 26554
Incompletes: 0
Non-ROA files: 0
...finished in 0:00:54.822463

--- Parsing IRR ---

Extracting afrinic.db.gz
Extracting apnic.db.route.gz
Extracting apnic.db.route6.gz
Extracting arin.db.gz
Extracting lacnic.db.gz
Extracting ripe.db.route.gz
Extracting ripe.db.route6.gz
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/lacnic.db
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/ripe.db.route
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/apnic.db.route6
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/apnic.db.route
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/arin.db
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/afrinic.db
Parsing /Users/FJ/projects/python/kartograf/out/1706536800/irr/ripe.db.route6
Found valid, unique entries: 1428528
...finished in 0:03:15.226518

--- Merging RPKI and IRR data ---

Parse base file to numpy arrays
Parse extra file to Pandas DataFrame
Filtering extra prefixes that were already included in the base file:

 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142853 /   142853 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142852 /   142852 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   142852 /   142852 |

Finished filtering! Originally 1428528 entries filtered down to 392620
Merging base file with filtered extra file
...finished in 0:53:42.974076

--- Parsing Routeviews pfx2as ---

Unzipping /Users/FJ/projects/python/kartograf/data/1706536800/collectors/routeviews_pfx2asn_ip4.txt.gz
Formatting /Users/FJ/projects/python/kartograf/out/1706536800/collectors/routeviews_pfx2asn_ip4.txt
Unzipping /Users/FJ/projects/python/kartograf/data/1706536800/collectors/routeviews_pfx2asn_ip6.txt.gz
Formatting /Users/FJ/projects/python/kartograf/out/1706536800/collectors/routeviews_pfx2asn_ip6.txt
Cleaning /Users/FJ/projects/python/kartograf/out/1706536800/collectors/pfx2asn.txt
...finished in 0:02:02.994326

--- Merging Routeviews and base data ---

Parse base file to numpy arrays
Parse extra file to Pandas DataFrame
Filtering extra prefixes that were already included in the base file:

 100.00% :::::::::::::::::::::::::::::::::::::::: |   119311 /   119311 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119311 /   119311 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |   119310 /   119310 |

Finished filtering! Originally 1193102 entries filtered down to 408934
Merging base file with filtered extra file
...finished in 1:24:50.374327

--- Sorting results ---

...finished in 0:00:11.480217

--- Finishing Kartograf ---

The SHA-256 hash of the result file is: 608bdb0121d116ca2b1b958dce6cc538d09ca775084065ad4314cd5c893a2800
Total runtime: 3:15:37.831740
```

</details>

**Comment by virtu** [comment]
My hash is `10b112366835653371cc7c4c6963f0e0464aa6483a5379d4e163b836b6f67570`.

**Comment by jurraca** [comment]
I got `05ee8c4a7e1363f5eb0e3888059093bffe788d77b60bb6814f1865ee443b1c04` as well. 

<details>
--- Start Kartograf ---                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                            
Kartograf version: 0.4.2                                                                                                                                                                                                                                                                    
Using rpki-client version 8.6.                                                                                                                                                                                                                                                              
Coordinated launch mode: Waiting until 1706536800 (2024-01-29 14:00:00 WET) to launch mapping process.                                                                                                                                                                                      
Countdown: 0 second(s)                                                                                                                                                                                                                                                                      
Starting...                                                                                                                                                                                                                                                                                 
The epoch for this run is: 1706536800 (2024-01-29 14:00:00 UTC, local: 2024-01-29 14:00:00 WET)                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                            
--- Fetching RPKI ---                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                            
Downloaded TAL for AFRINIC to /home/base/code/kartograf/data/1706536800/rpki/tals/afrinic.tal                                                                                                                                                                                               
Downloaded TAL for APNIC to /home/base/code/kartograf/data/1706536800/rpki/tals/apnic.tal                                                                                                                                                                                                   
Downloaded TAL for ARIN to /home/base/code/kartograf/data/1706536800/rpki/tals/arin.tal                                                                                                                                                                                                     
Downloaded TAL for LACNIC to /home/base/code/kartograf/data/1706536800/rpki/tals/lacnic.tal                                                                                                                                                                                                 
Downloaded TAL for RIPE to /home/base/code/kartograf/data/1706536800/rpki/tals/ripe.tal                                                                                                                                                                                                     
Downloading RPKI Data                                                                                                                                                                                                                                                                       
...finished in 0:03:55.760242                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                            
--- Fetching IRR ---                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            
Downloading afrinic.db.gz                                                                                                                                                                                                                                                                   
Downloading apnic.db.route.gz                                                                                                                                                                                                                                                               
Downloading apnic.db.route6.gz                                                                                                                                                                                                                                                              
Downloading arin.db.gz                                                                                                                                                                                                                                                                      
Downloading lacnic.db.gz                                                                                                                                                                                                                                                                    
Downloading ripe.db.route.gz                                                                                                                                                                                                                                                                
Downloading ripe.db.route6.gz                                                                                                                                                                                                                                                               
...finished in 0:00:48.721641                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                            
--- Fetching Routeviews pfx2as ---                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            
Downloading https://publicdata.caida.org/datasets/routing/routeviews-prefix2as/2024/01/routeviews-rv2-20240127-1200.pfx2as.gz                                                                                                                                                               
Downloading https://publicdata.caida.org/datasets/routing/routeviews6-prefix2as/2024/01/routeviews-rv6-20240128-0600.pfx2as.gz                                            
...finished in 0:00:07.665294                                                  
                                       
--- Validating RPKI ---                                                                                                                                        
                                                                                                                                                               
Validating RPKI ROAs                                                                                                                                           
218376 raw RKPI ROA files found.                                                                                                                               
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 218376/218376 [24:52<00:00, 146.36it/s] 
218376 RKPI ROAs validated and saved to /home/base/code/kartograf/out/1706536800/rpki/rpki_raw.json                                                            
...finished in 0:25:08.308967                                                                                                                                  
                                                                                                                                                               
--- Parsing RPKI ---                                                                                                                                           
                                                                                                                                                               
Parsing 218376 ROAs                                                                                                                                            
Result entries written: 457178                                                                                                                                 
Duplicates found: 57649                                                                                                                                        
Invalids found: 26459                                                                                                                                          
Incompletes: 0                                                                                                                                                 
Non-ROA files: 0                       
...finished in 0:01:27.321095                                                  
                                                                               
--- Parsing IRR ---                    
                                                                                                                                                               
Extracting afrinic.db.gz               
Extracting apnic.db.route.gz  
Extracting apnic.db.route6.gz                                                                                                                                  
Extracting arin.db.gz        
Extracting lacnic.db.gz     
Extracting ripe.db.route.gz                                            
Extracting ripe.db.route6.gz                                           
Parsing /home/base/code/kartograf/out/1706536800/irr/afrinic.db                                                                               
Parsing /home/base/code/kartograf/out/1706536800/irr/arin.db                                                                                  
Parsing /home/base/code/kartograf/out/1706536800/irr/ripe.db.route6                                                                           
Parsing /home/base/code/kartograf/out/1706536800/irr/apnic.db.route6                                                                          
Parsing /home/base/code/kartograf/out/1706536800/irr/lacnic.db                                                                                
Parsing /home/base/code/kartograf/out/1706536800/irr/ripe.db.route                                                                            
Parsing /home/base/code/kartograf/out/1706536800/irr/apnic.db.route                                                                           
Found valid, unique entries: 1428528                                   
...finished in 0:05:22.367182                                          

--- Merging RPKI and IRR data ---                                      

Parse base file to numpy arrays                                        
Parse extra file to Pandas DataFrame                                   
Filtering extra prefixes that were already included in the base file:                                                                         

 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   178566 /   178566 |                                                                                                                                                                                                                   

Finished filtering! Originally 1428528 entries filtered down to 392496                                                                        
Merging base file with filtered extra file                                                                                                    
...finished in 2:48:24.283310                                          

--- Parsing Routeviews pfx2as ---                                      

Unzipping /home/base/code/kartograf/data/1706536800/collectors/routeviews_pfx2asn_ip4.txt.gz                                                                                                                                                                                                
Formatting /home/base/code/kartograf/out/1706536800/collectors/routeviews_pfx2asn_ip4.txt                                                                                                                                                                                                   
Unzipping /home/base/code/kartograf/data/1706536800/collectors/routeviews_pfx2asn_ip6.txt.gz                                                                                                                                                                                                
Formatting /home/base/code/kartograf/out/1706536800/collectors/routeviews_pfx2asn_ip6.txt                                                                                                                                                                                                   
Cleaning /home/base/code/kartograf/out/1706536800/collectors/pfx2asn.txt                                                                      
...finished in 0:03:17.355637                                          

--- Merging Routeviews and base data ---                                                                                                      

Parse base file to numpy arrays                                        
Parse extra file to Pandas DataFrame                                   
Filtering extra prefixes that were already included in the base file:                                                                         

 100.00% :::::::::::::::::::::::::::::::::::::::: |   149138 /   149138 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149138 /   149138 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149138 /   149138 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149138 /   149138 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149138 /   149138 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149138 /   149138 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149137 /   149137 |                                                                                                                                                                                                                   
 100.00% :::::::::::::::::::::::::::::::::::::::: |   149137 /   149137 |                                                                                                                                                                                                                   

Finished filtering! Originally 1193102 entries filtered down to 408895                                                                        
Merging base file with filtered extra file                                                                                                    
...finished in 4:38:28.713783                                          

--- Sorting results ---                                                

...finished in 0:00:19.077419                                          

--- Finishing Kartograf ---                                            

The SHA-256 hash of the result file is: 05ee8c4a7e1363f5eb0e3888059093bffe788d77b60bb6814f1865ee443b1c04                                                                                                                                                                                    
Total runtime: 8:07:21.533600
</details>

I didn't pull the latest changes before running so don't have the file hashes in the logs, sorry :disappointed:

**Comment by Emzy** [comment]
I got
'''
The SHA-256 hash of the result file is: 05ee8c4a7e1363f5eb0e3888059093bffe788d77b60bb6814f1865ee443b1c04
Total runtime: 15:17:39.326837
'''

**Comment by fjahr** [comment]
Ok, so, for now, we stand 3/5 for `05ee8c4a7e1363f5eb0e3888059093bffe788d77b60bb6814f1865ee443b1c04`, that would be good enough. I'll wait until tomorrow in case we get more results but in the meantime can one of those who got this result share their result file here?

And if someone else would like to open the PR, similar to https://github.com/fjahr/asmap-data/pull/6 please go ahead :) This time it should just work without the manual cleanup step.

**Comment by fjahr** [comment]
> Would a multistep coordinated launch help here? Start downloading the IRR data, e.g., 20 minute after take-off? Or do everything in parallel and hope they all run their FTP servers on some Unix, so the files stay available ([#7 (comment)](https://github.com/fjahr/asmap-data/issues/7#issuecomment-1913157727)).

I'm still worried about everything parallel because of RPKI. Starting at a later time like 20min could work, though I'm not sure yet what a good default would be. I have a really fast connection but this time it took almost 10 min to get RPKI. Let me do a bit more research to decide what would be the better next step.

**Comment by jurraca** [comment]
Result file @fjahr [final_result.zip](https://github.com/fjahr/asmap-data/files/14114901/final_result.zip)

**Comment by Sjors** [comment]
The SHA-256 hash of the result file is: 05ee8c4a7e1363f5eb0e3888059093bffe788d77b60bb6814f1865ee443b1c04
Total runtime: 2:43:00.106239

**Comment by fjahr** [comment]
Awesome! That means in the end we got 4/6 matches on `05ee8c4a7e1363f5eb0e3888059093bffe788d77b60bb6814f1865ee443b1c04`, that's great! I have opened the corresponding PR to add the encoded version: https://github.com/fjahr/asmap-data/pull/10 It would be great if some of you could confirm the result (using the file from https://github.com/fjahr/asmap-data/issues/9#issuecomment-1919547694 if you did get the matching result yourself).
